export const CORPORATE_DETAILS = {
  companyName: {
    componentType: 'autoSuggest',
    options: [],
    label: 'Search company name',
    value: '',
    disabled: false,
    isError: false,
    id: 'companyName',
    errorMessage: 'Please select company name',
    required: true,
    selectedItem: { id: '', companyName: '' },
  },
  relationshipManagerName: {
    userId: '',
    componentType: 'input',
    value: '',
    label: 'Relationship manager name',
    isError: false,
    disabled: true,
    required: true,
    errorMessage: 'Please enter relationship manager name',
  },
  relationshipManagerPhone: {
    componentType: 'input',
    value: '',
    disabled: true,
    label: 'Relationship manager phone ',
    errorMessage: 'Please enter relationship manager phone',
    isError: false,
  },
  relationshipManagerEmail: {
    componentType: 'input',
    value: '',
    label: 'Relationship manager email',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter relationship manager email',
  },
  gstEntityName: {
    componentType: 'gstDropdown',
    disabled: true,
    options: [{}],
    selectedItem: {},
    dynamicPlaceholder: true,
    required: true,
    requiredText: '*',
    placeholderText: 'GST entity name',
    isError: false,
    errorMessage: 'Please enter GST entity name',
  },
  gSTNumber: {
    componentType: 'input',
    value: '',
    label: 'GSTIN',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GSTIN',
  },
  gSTCompanyName: {
    componentType: 'input',
    value: '',
    label: 'GST company name',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST company name',
  },
  gSTCompanyAddress: {
    componentType: 'input',
    value: '',
    label: 'GST address',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST address',
  },
  gSTCompanyPinCode: {
    componentType: 'input',
    value: '',
    label: 'GST pincode',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST pincode',
  },
}
