export const CORPORATE_DETAILS = {
  companyName: {
    componentType: 'autoSuggest',
    options: [],
    label: 'Search company name',
    value: '',
    disabled: false,
    isError: false,
    id: 'companyName',
    errorMessage: 'Please select company name',
    required: true,
    selectedItem: { id: '', companyName: '' },
  },
  relationshipManagerName: {
    userId: '',
    componentType: 'input',
    value: '',
    label: 'Relationship manager name',
    isError: false,
    disabled: true,
    required: true,
    errorMessage: 'Please enter relationship manager name',
  },
  relationshipManagerPhone: {
    componentType: 'input',
    value: '',
    disabled: true,
    label: 'Relationship manager phone ',
    errorMessage: 'Please enter relationship manager phone',
    isError: false,
  },
  relationshipManagerEmail: {
    componentType: 'input',
    value: '',
    label: 'Relationship manager email',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter relationship manager email',
  },
  gstEntityName: {
    componentType: 'gstDropdown',
    disabled: true,
    options: [{}],
    selectedItem: {},
    dynamicPlaceholder: true,
    required: true,
    requiredText: '*',
    placeholderText: 'GST entity name',
    isError: false,
    errorMessage: 'Please enter GST entity name',
  },
  gSTNumber: {
    componentType: 'input',
    value: '',
    label: 'GSTIN',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GSTIN',
  },
  gSTCompanyName: {
    componentType: 'input',
    value: '',
    label: 'GST company name',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST company name',
  },
  gSTCompanyAddress: {
    componentType: 'input',
    value: '',
    label: 'GST address',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST address',
  },
  gSTCompanyPinCode: {
    componentType: 'input',
    value: '',
    label: 'GST pincode',
    isError: false,
    disabled: true,
    errorMessage: 'Please enter GST pincode',
  },
}

export const TRIP_MAPPING = {
    tripId: {
      id: 'tripId',
      isError: false,
      componentType: 'input',
      label: 'Trip ID',
      disabled: true,
      value: '',
      errorMessage: 'Please enter a valid trip ID',
      type: 'text',
    },
  }

export const BOOKING_DETAILS = {
  origin: {
    componentType: 'autoSuggest-citySearch',
    inputProps: {
      placeholder: "Departure city or airport",
      dynamicPlaceholder: true,
      required: true,
      errorMessage: 'Please enter departure city or airport',
      id: "origin",
      requiredText: '*',
      isError: false,
    },
    selectedItem: {},
    options: [],
    itemTextKey: "text",
    itemValueKey: "value",
    key: "origin"
  },
  destination: {
    componentType: 'autoSuggest-citySearch',
    inputProps: {
      placeholder: "Arrival city or airport",
      dynamicPlaceholder: true,
      required: true,
      errorMessage: 'Please enter arrival city or airport',
      id: "destination",
      requiredText: '*',
      isError: false,
    },
    selectedItem: {},
    options: [],
    itemTextKey: "text",
    itemValueKey: "value",
    key: "destination"
  },
  depDate: {
    componentType: "dateSelection",
    id: "depDate",
    name: "depDate",
    value: "",
    isError: false,
    requiredText: '*',
    required: true,
    errorMessage: "Please select departure Date",
    dynamicPlaceholder: true,
    placeholder: "Departure Date",
  },

  noOfTravellers: {
    componentType: 'numberInput',
    value: 1,
    placeholder: 'Guest count ',
    required: true,
    dynamicPlaceholder: true,
    requiredText: '*',
    errorMessage: "Please enter guest count",
    isError: false,
  },
}

export const FLIGHT_DETAILS = {
      subTripId: {
        key: "subTripID",
        componentType: "dropdown",
        options: [{}],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: false,
        requiredText: "*",
        placeholderText: "Select sub-trip ID",
        isError: false,
        errorMessage: "Please enter sub-trip ID",
        disabled: true,
        id: 'subTripId',
        selectKey: "value",
        textKey: "text",
      },
      ticketingSource: {
        componentType: 'dropdown',
        options: [],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: true,
        requiredText: '*',
        placeholderText: "Ticketing sources",
        isError: false,
        errorMessage: "Please select ticketing sources",
      },
      airline: {
        componentType: 'dropdown',
        options: [],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: true,
        requiredText: '*',
        placeholderText: "Airline",
        isError: false,
        errorMessage: "Please select airline",
      },
      flightNumber: {
        componentType: 'input',
        value: '',
        placeholder: 'Flight number',
        required: true,
        dynamicPlaceholder: true,
        requiredText: '*',
        errorMessage: "Please enter flight number",
        isError: false,
      },
      class: {
        componentType: 'dropdown',
        options: [],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: true,
        requiredText: '*',
        placeholderText: "Class",
        isError: false,
        errorMessage: "Please select class",
      },
      pnr: {
        componentType: 'input',
        value: '',
        placeholder: 'PNR number',
        required: true,
        dynamicPlaceholder: true,
        requiredText: '*',
        errorMessage: "Please enter PNR number",
        isError: false,
      },
      depDateTime: {
        componentType: 'timePickerInput',
        value: "",
        isError: false,
        errorMessage: "Please select valid departure time ",
        showTimeSelect: true,
        timeIntervals: 5,
        dynamicPlaceholder: true,
        placeholder: "Departure time",
        mainClassName: "react-time-picker-wrapper input-field",
        className: " time-picker input-field",
        requiredText: '*',
        required: true,
      },
      arrDateTime: {
        componentType: 'timePickerInput',
        value: "",
        isError: false,
        errorMessage: "Please select valid arrival time ",
        showTimeSelect: true,
        dynamicPlaceholder: true,
        timeIntervals: 5,
        placeholder: "Arrival time",
        mainClassName: "react-time-picker-wrapper input-field",
        className: " time-picker input-field",
        requiredText: '*',
        required: true,
      },
      depTerminal: {
        componentType: 'dropdown',
        options: [],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: true,
        requiredText: '*',
        placeholderText: "Departure terminal",
        isError: false,
        errorMessage: "Please select departure terminal",
      },
      arrTerminal: {
        componentType: 'dropdown',
        options: [],
        selectedItem: {},
        hideValue: true,
        dynamicPlaceholder: true,
        required: true,
        requiredText: '*',
        placeholderText: "Arrival terminal",
        isError: false,
        errorMessage: "Please select arrival terminal",
      
  }
}
  // stopDetails: {
  //   heading: "Stop details",
  //   formObj: {
  //     stop: {
  //       componentType: 'dropdown',
  //       options: [],
  //       selectedItem: {},
  //       hideValue: true,
  //       dynamicPlaceholder: true,
  //       required: true,
  //       requiredText: '*',
  //       placeholderText: "Stop",
  //       isError: false,
  //       errorMessage: "Please select Stop",
  //     },
  //   }
  // },
  // stopInfo: {
  //   heading: "stop info",
  //   formObj: []
  // },
  // baggageDetails: {
  //   heading: "Baggage details",
  //   formObj: {
  //     cabin: {
  //       componentType: 'input',
  //       value: 7,
  //       type: "number",
  //       placeholder: 'Cabin',
  //       dynamicPlaceholder: true,
  //       isError: false,
  //       required: true,
  //       requiredText: '*',
  //       errorMessage: "Please enter cabin upto 100kg",
  //       maxLength: 3,
  //     },
  //     checkIn: {
  //       componentType: 'input',
  //       value: 15,
  //       type: "number",
  //       placeholder: 'Check in',
  //       dynamicPlaceholder: true,
  //       isError: false,
  //       required: true,
  //       requiredText: '*',
  //       errorMessage: "Please enter check in upto 100kg",
  //       maxLength: 3,
  //     },
  //   }
  // }